### ISSUE TITLE
[meta] Developer experience audit

### ISSUE THREAD

**Issue by RichardLitt** [probot/friction#35]
:wave: Hey there! This is the developer experience audit from @mntnr for this repository. I've added in my thoughts below, in the form of a checklist. Looking forward to seeing what you think; let's see if we can resolve all of the open issues and make this repository shine ✨ 💖 ✨

# Repository Review: probot/friction

> a place to talk about any friction experienced using Probot.

_For notes on anything crossed out, look below. Note: I use `[~]` to mean that I have proposed a fix in a PR. I know it doesn't render properly in Markdown, but it works pretty well otherwise for that purpose. If I think that something is fine, even if it isn't valid according to this checklist, I've checked it off and included a note._

### Reviewing the Repository Docs

- [x] Is there a README?
  - [ ] Does it follow [standard-readme](https://github.com/RichardLitt/standard-readme)? _No, totally OK_.
  - [x] Is it spellchecked?
- [~] Is there a Code of Conduct, such as the [Contributor Covenant](https://github.com/simonv3/covenant-generator)?
  - [~] Is it mentioned in the Contribute section of the README? (Note: this isn't needed if you mention it in your CONTRIBUTE.md and it is in this repository.)
  - [~] Does it reference an email address for violations?
  - [ ] Does it reference a second email address? _This is most likely OK._
- [ ] Is there a `LICENSE` file?
  - [ ] Is the year correct?
- [x] Is there a `.github` or `docs` folder?
  - [ ] Is there an `ISSUE_TEMPLATE.md`?
  - [ ] Is there a `PULL_REQUEST_TEMPLATE.md`?
- [~] Is there a `CONTRIBUTING.md` file?
  - [~] Does it mention what sort of issues you'd like?
  - [~] Does it point to a community chat program, like Slack?
  - [~] Does it specify where to ask questions on process?
  - [ ] Does it explain labels used in the issues?
- [ ] Is there a `CHANGELOG`?
  - [ ] If there isn't, are notes included in the project's releases?
- [x] Does this pass [`alex`](https://github.com/wooorm/alex) adequately? Run `alex *.md`.
- [x] Does the repository name itself pass on http://wordsafety.com?

### Issues and Pull Requests
- [x] Are there an acceptable amount of issues?
- [x] Are an acceptable amount of issues less than six months old? _Stale bot_
- [x] Are there useful issue labels?
- [x] Are the labels being used?

### Bots

_Note: Neither of these are necessary, but they can help with some things. Check out https://probot.github.io/ for some tools._

- [x] Are there bots enabled? _Stale_
- [~] Are the bots listed in the Contribute or Readme files so that users can expect to interact with them?

### Metadata
- [x] Is there a description on GitHub?
  - [~] Does the description match the README?
- [x] Are the topics useful?
- [ ] Is there a website?

### TODO

- [ ] Capitalize the first letter `a` in the GitHub description.
- [ ] Add the Creative Commons Zero license, or some other permissive license for issues and docs.
- [~] Add a link to your Slack!
- [ ] Consider adding a secondary email to the Code of Conduct as a contact - someone may have an issue with _you_ but not want to tell you directly. I know, this idea may be awkward. But you will give them an option in case they do have an option, and this may be good for the overall health of the project.
- [ ] Consider adding `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` files to your repository.
- [~] I would point to a particularly good friction issue, and a poor issue, in the Contributing. This may help newcomers know what to do.

## Contribute back?

This checklist is open source! If you have suggestions or think it could be better, contribute back on [mntnr/audit-templates](https://github.com/mntnr/audit-templates).

Thank you!
